name: Font Library
baseurl: /font-library
url: http://katydecorah.com
description: An open source project to tag and organize Google Fonts.
permalink: pretty
image:
github: https://github.com/katydecorah/font-library
contributing: https://github.com/katydecorah/font-library/blob/gh-pages/CONTRIBUTING.md

angular: 1.4.8
jquery: 2.1.4
underscore: 1.8.3

port: 4000
host: 127.0.0.1

exclude:
  - "*.lock"
  - "Gemfile"
  - ".scss-lint.yml"
  - "Rakefile"
  - ".travis.yml"
  - "LICENSE"
  - "README.md"
  - node_modules

sass:
  style: :compressed
